version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8080:8080"
    healthcheck:
      test: "bash /opt/keycloak/health-check.sh"
      interval: 5s
      timeout: 10s
      retries: 12
    volumes:
      - ./keycloak/extra/health-check.sh:/opt/keycloak/health-check.sh
      - ./keycloak/realms/:/opt/keycloak/data/import
      - ./keycloak/providers/:/opt/keycloak/providers