version: '3.8'

services:
  keycloak-ssi-idp:
    build:
      context: .
      dockerfile: ./Dockerfile
    #    image: public.ecr.aws/dizme.io/keycloak-ssi-idp:latest
    container_name: keycloak-ssi-idp
    ports:
      - "88:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_VERIFIER_URL=https://verifier-backend.eudiw.dev
      - NEXT_PUBLIC_OIDC4VP_SCHEME=eudi-openid4vp://
      - NEXT_PUBLIC_PRESENTATION_FORMAT=mso_mdoc